// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./interfaces/ICompliance.sol";
import "./RevocationRegistry.sol";
import "./IdentityTreeManager.sol";

/// @title ZKComplianceModule - ZK-powered ERC-3643 compliance module
/// @notice Replaces transparent identity checks with ZK proof verification
/// @dev Implements the ICompliance interface so it drops in to any ERC-3643 token
contract ZKComplianceModule is ICompliance {
    // The auto-generated Groth16 verifier
    address public immutable verifier;
    RevocationRegistry public immutable revocationRegistry;
    IdentityTreeManager public immutable identityTreeManager;

    // Freshness window: proofs must be submitted within this window
    uint256 public freshnessWindow = 1 hours;

    // Track when each address last submitted a valid proof
    mapping(address => uint256) public lastProofTimestamp;

    // The bound token
    address public boundToken;
    address public owner;

    event ProofVerified(address indexed user, uint256 timestamp);
    event TransferChecked(address indexed from, address indexed to, bool result);

    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }

    constructor(
        address _verifier,
        address _revocationRegistry,
        address _identityTreeManager
    ) {
        verifier = _verifier;
        revocationRegistry = RevocationRegistry(_revocationRegistry);
        identityTreeManager = IdentityTreeManager(_identityTreeManager);
        owner = msg.sender;
    }

    /// @notice Submit a ZK proof of compliance
    /// @dev Called by the user before initiating a transfer
    function submitProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicSignals
    ) external {
        // Public signals order (must match circuit):
        // [0] = valid (output, must be 1)
        // [1] = identityRoot
        // [2] = revocationRoot
        // [3] = currentTimestamp
        // [4] = issuerPubKeyAx
        // [5] = issuerPubKeyAy
        // [6] = requiredClaimTopic

        // Check output is valid
        require(publicSignals[0] == 1, "Proof output: not valid");

        // Check roots match current on-chain state
        require(
            bytes32(publicSignals[1]) == identityTreeManager.getIdentityRoot(),
            "Identity root mismatch"
        );
        require(
            bytes32(publicSignals[2]) == revocationRegistry.getRevocationRoot(),
            "Revocation root mismatch"
        );

        // Check timestamp is recent (within 5 minutes)
        require(
            block.timestamp - publicSignals[3] < 5 minutes,
            "Proof timestamp too old"
        );

        // Verify the Groth16 proof
        // The verifier contract has a verifyProof function auto-generated by snarkjs
        (bool success, bytes memory data) = verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[7])",
                a, b, c,
                [publicSignals[0], publicSignals[1], publicSignals[2],
                 publicSignals[3], publicSignals[4], publicSignals[5],
                 publicSignals[6]]
            )
        );
        require(success && abi.decode(data, (bool)), "Invalid ZK proof");

        // Record proof timestamp
        lastProofTimestamp[msg.sender] = block.timestamp;
        emit ProofVerified(msg.sender, block.timestamp);
    }

    /// @notice ERC-3643 compliance hook - called before every transfer
    function canTransfer(
        address from,
        address to,
        uint256 /* amount */
    ) external view override returns (bool) {
        // Both sender and receiver must have recent valid proofs
        // A timestamp of 0 means no proof was ever submitted
        bool fromCompliant = lastProofTimestamp[from] > 0 &&
            (block.timestamp - lastProofTimestamp[from]) < freshnessWindow;
        bool toCompliant = lastProofTimestamp[to] > 0 &&
            (block.timestamp - lastProofTimestamp[to]) < freshnessWindow;

        bool result = fromCompliant && toCompliant;
        return result;
    }

    // === ERC-3643 interface stubs ===
    function transferred(address, address, uint256) external override {}
    function created(address, uint256) external override {}
    function destroyed(address, uint256) external override {}

    function bindToken(address token) external override onlyOwner {
        boundToken = token;
    }

    function unbindToken(address) external override onlyOwner {
        boundToken = address(0);
    }

    // === Admin ===
    function setFreshnessWindow(uint256 _window) external onlyOwner {
        freshnessWindow = _window;
    }
}
